
import { ContentItem, Elements } from './node_modules/@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.1.0'
 * Timestamp: Tue Feb 04 2020 13:38:01 GMT-0500 (Eastern Standard Time)
 */
export class Article extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((elementName) => {
                if (elementName === 'topics_image') {
                    return 'topicsImage';
                }
                if (elementName === 'linked_content') {
                    return 'linkedContent';
                }
                if (elementName === 'background_image') {
                    return 'backgroundImage';
                }
                return elementName;
            })
        });
    }
}
