
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.1.0'
 * Timestamp: Tue Feb 04 2020 13:38:01 GMT-0500 (Eastern Standard Time)
 */
export class Speaker extends ContentItem {
  constructor() {
    super({
      richTextResolver: (rawElement) => {
        debugger;
      },
      itemResolver: (rawElement) => {
        debugger;
      },
      linkedItemResolver: (rawElement) => {
        debugger;
      },
    });
  }
}
