
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.1.0'
 * Timestamp: Tue Feb 04 2020 13:38:01 GMT-0500 (Eastern Standard Time)
 */
export class TestType extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((elementName) => {
                if (elementName === 'test_title') {
                    return 'testTitle';
                }
                if (elementName === 'test_body') {
                    return 'testBody';
                }
                if (elementName === 'test_image') {
                    return 'testImage';
                }
                return elementName;
            })
        });
    }
}
