import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.1.0'
 * Timestamp: Tue Feb 04 2020 13:38:01 GMT-0500 (Eastern Standard Time)
 */
export class Topic extends ContentItem {
  constructor() {
    super({
      richTextResolver: topic => {
        debugger;
      },
      propertyResolver: elementName => {
        if (elementName === 'linked_highlighted_video') {
          return 'linkedHighlightedVideo';
        }
        if (elementName === 'key_locations') {
          return 'keyLocations';
        }
        if (elementName === 'schedule_items') {
          return 'scheduleItems';
        }
        if (elementName === 'exhibitor_items') {
          return 'exhibitorItems';
        }
        if (elementName === 'linked_topic') {
          return 'linkedTopic';
        }
        if (elementName === 'linked_videos') {
          return 'linkedVideos';
        }
        if (elementName === 'background_image') {
          return 'backgroundImage';
        }
        if (elementName === 'linked_bottom_content') {
          return 'linkedBottomContent';
        }
        if (elementName === 'linked_top_content') {
          return 'linkedTopContent';
        }
        if (elementName === 'callout_text') {
          return 'calloutText';
        }
        if (elementName === 'linked_topic_content') {
          return 'linkedTopicContent';
        }
        if (elementName === 'callout_statistic') {
          return 'calloutStatistic';
        }
        return elementName;
      }
    });
  }
}

// export class Movie extends ContentItem {
//   public title: Elements.TextElement;
//   public stars: Elements.LinkedItemsElement<Actor>[];
// }